export const MUSCLES = {
  flat_db_press: {p: ["chest", "triceps"], s: ["front delts"]},
  incline_db_press: {p: ["upper chest", "front delts"], s: ["triceps"]},
  squeeze_press: {p: ["chest", "triceps"], s: ["front delts"]},
  db_fly: {p: ["chest"], s: ["front delts"]},
  incline_db_fly: {p: ["upper chest"], s: ["front delts"]},
  cs_db_row: {p: ["upper back", "lats"], s: ["biceps", "rear delts"]},
  seated_db_press: {p: ["shoulders", "triceps"], s: ["upper chest"]},
  standing_ohp: {p: ["shoulders", "triceps"], s: ["core"]},
  arnold_press: {p: ["shoulders", "triceps"], s: ["upper chest"]},
  push_press: {p: ["shoulders", "triceps"], s: ["quads", "core"]},
  lateral_raise: {p: ["side delts"], s: ["traps"]},
  seated_lateral_raise: {p: ["side delts"], s: ["traps"]},
  rear_delt_fly: {p: ["rear delts"], s: ["upper back"]},
  rear_delt_raise: {p: ["rear delts"], s: ["upper back"]},
  hammer_curl: {p: ["biceps", "forearms"], s: []},
  db_rdl: {p: ["hamstrings", "glutes"], s: ["lower back"]},
  stiff_leg_dl: {p: ["hamstrings", "glutes"], s: ["lower back"]},
  db_good_morning: {p: ["hamstrings", "lower back"], s: ["glutes"]},
  walking_lunge: {p: ["quads", "glutes"], s: ["hamstrings", "core"]},
  reverse_lunge: {p: ["quads", "glutes"], s: ["hamstrings"]},
  bulgarian: {p: ["quads", "glutes"], s: ["hamstrings", "core"]},
  db_step_up: {p: ["quads", "glutes"], s: ["hamstrings"]},
  lateral_lunge: {p: ["quads", "adductors"], s: ["glutes"]},
  standing_calf: {p: ["calves"], s: []},
  seated_calf: {p: ["calves"], s: []},
  single_leg_calf: {p: ["calves"], s: []},
  db_shrug: {p: ["traps"], s: ["forearms"]},
  renegade_row: {p: ["lats", "core"], s: ["biceps", "shoulders"]},
  farmer_carry: {p: ["forearms", "core"], s: ["traps", "glutes"]},
  db_front_squat: {p: ["quads", "glutes"], s: ["core", "upper back"]},
  shoulder_circles: {p: ["side delts"], s: ["rotator cuff"]},
  goblet_squat: {p: ["quads", "glutes"], s: ["core"]},
  sumo_squat: {p: ["quads", "adductors"], s: ["glutes"]},
  db_pullover: {p: ["lats", "chest"], s: ["triceps"]},
  single_arm_row: {p: ["lats", "upper back"], s: ["biceps", "core"]},
  concentration_curl: {p: ["biceps"], s: []},
  oh_tri_ext: {p: ["triceps"], s: []},
  tri_kickback: {p: ["triceps"], s: []},
  cross_hammer_curl: {p: ["biceps", "forearms"], s: []},
  glute_bridge: {p: ["glutes"], s: ["hamstrings"]},
  hip_thrust: {p: ["glutes"], s: ["hamstrings"]},
  single_leg_rdl: {p: ["hamstrings", "glutes"], s: ["core", "ankles"]},
  russian_twist: {p: ["obliques"], s: ["core"]},
  decline_situp: {p: ["core"], s: ["hip flexors"]},
  db_side_bend: {p: ["obliques"], s: []},
  weighted_dead_bug: {p: ["core"], s: ["hip flexors"]},
  suitcase_carry: {p: ["obliques", "forearms"], s: ["traps"]},
  weighted_leg_raise: {p: ["core", "hip flexors"], s: ["forearms"]},
  twist_lunge: {p: ["quads", "obliques"], s: ["glutes"]},
  back_extension: {p: ["lower back", "glutes"], s: ["hamstrings"]},
  ez_curl: {p: ["biceps"], s: ["forearms"]},
  ez_skullcrusher: {p: ["triceps"], s: []},
  ez_upright_row: {p: ["side delts", "traps"], s: ["biceps"]},
  ez_21s: {p: ["biceps"], s: ["forearms"]},
  ez_oh_ext: {p: ["triceps"], s: []},
  close_grip_press: {p: ["triceps", "chest"], s: ["front delts"]},
  incline_curl: {p: ["biceps"], s: []},
  lat_pulldown: {p: ["lats"], s: ["biceps", "upper back"]},
  seated_row: {p: ["upper back", "lats"], s: ["biceps"]},
  cable_crossover: {p: ["chest"], s: ["front delts"]},
  cable_curl: {p: ["biceps"], s: []},
  face_pull: {p: ["rear delts", "rotator cuff"], s: ["upper back"]},
  leg_curl: {p: ["hamstrings"], s: []},
  cable_crunch: {p: ["core"], s: []},
  woodchop: {p: ["obliques"], s: ["core", "shoulders"]},
  pallof_press: {p: ["core", "obliques"], s: []},
  pullup: {p: ["lats", "biceps"], s: ["upper back", "forearms"]},
  chinup: {p: ["lats", "biceps"], s: ["upper back"]},
  wide_pullup: {p: ["lats"], s: ["upper back", "biceps"]},
  pushup_burnout: {p: ["chest", "triceps"], s: ["front delts", "core"]},
  feet_elev_pushup: {p: ["upper chest", "front delts"], s: ["triceps", "core"]},
  diamond_pushup: {p: ["triceps", "chest"], s: ["front delts"]},
  bench_dip: {p: ["triceps"], s: ["chest", "front delts"]},
  inverted_row: {p: ["upper back", "lats"], s: ["biceps", "core"]},
  plank: {p: ["core"], s: ["shoulders"]},
  side_plank: {p: ["obliques"], s: ["glutes"]},
  side_plank_reach: {p: ["obliques"], s: ["shoulders"]},
  copenhagen: {p: ["adductors", "obliques"], s: []},
  hollow_hold: {p: ["core"], s: ["hip flexors"]},
  hollow_rock: {p: ["core"], s: ["hip flexors"]},
  dead_bug: {p: ["core"], s: []},
  bird_dog: {p: ["core", "lower back"], s: ["glutes"]},
  shoulder_taps: {p: ["core", "shoulders"], s: []},
  plank_up_down: {p: ["core", "triceps"], s: ["shoulders"]},
  ab_wheel: {p: ["core"], s: ["lats"]},
  mountain_climber: {p: ["core", "hip flexors"], s: ["shoulders"]},
  flutter_kicks: {p: ["core", "hip flexors"], s: []},
  bicycle_crunch: {p: ["core", "obliques"], s: []},
  reverse_crunch: {p: ["core"], s: ["hip flexors"]},
  v_up: {p: ["core", "hip flexors"], s: []},
  hanging_knee_raise: {p: ["core", "hip flexors"], s: ["forearms"]},
  hanging_leg_raise: {p: ["core", "hip flexors"], s: ["forearms"]},
  hanging_knee_twist: {p: ["obliques", "hip flexors"], s: ["forearms"]},
  toes_to_bar: {p: ["core", "lats"], s: ["hip flexors", "forearms"]},
  oblique_knee_raise: {p: ["obliques", "hip flexors"], s: ["forearms"]},
  archer_pushup: {p: ["chest", "triceps"], s: ["core"]},
  wide_pushup: {p: ["chest"], s: ["front delts", "triceps"]},
  spiderman_pushup: {p: ["chest", "obliques"], s: ["hip flexors"]},
  thruster: {p: ["quads", "shoulders"], s: ["glutes", "triceps"]},
  bench_stepover: {p: ["quads", "glutes"], s: ["calves"]},
  burpee_over_bells: {p: ["full body"], s: ["chest", "quads"]},
  punch_out: {p: ["shoulders"], s: ["obliques", "triceps"]},
  man_maker: {p: ["full body"], s: ["lats", "shoulders"]},
  devil_press: {p: ["full body"], s: ["glutes", "shoulders"]},
  hang_clean: {p: ["glutes", "traps"], s: ["quads", "shoulders"]},
  db_bent_row: {p: ["upper back", "lats"], s: ["biceps", "lower back"]},
  clean_and_press: {p: ["glutes", "shoulders"], s: ["quads", "traps"]},
  overhead_carry: {p: ["shoulders", "core"], s: ["traps"]},
  alt_snatch: {p: ["glutes", "shoulders"], s: ["hamstrings", "traps"]},
  turkish_getup: {p: ["core", "shoulders"], s: ["glutes", "hips"]},
  single_arm_press: {p: ["shoulders", "triceps"], s: ["obliques"]},
  single_arm_floor_press: {p: ["chest", "triceps"], s: ["core"]},
  goblet_cossack: {p: ["adductors", "quads"], s: ["glutes", "hips"]},
  suitcase_deadlift: {p: ["glutes", "obliques"], s: ["hamstrings", "forearms"]},
  jefferson_curl: {p: ["hamstrings", "lower back"], s: ["spine"]},
  backpack_thruster: {p: ["quads", "shoulders"], s: ["glutes"]},
  backpack_row: {p: ["lats", "upper back"], s: ["biceps"]},
  backpack_squat: {p: ["quads", "glutes"], s: ["core"]},
  backpack_carry: {p: ["forearms", "core"], s: ["traps"]},
  single_arm_cable_row: {p: ["lats", "upper back"], s: ["biceps", "obliques"]},
  cable_pull_through: {p: ["glutes", "hamstrings"], s: []},
  half_kneel_woodchop: {p: ["obliques"], s: ["core", "shoulders"]},
  cable_rotation: {p: ["obliques"], s: ["core"]},
  cable_antirotation_hold: {p: ["core", "obliques"], s: []},
  half_kneel_pulldown: {p: ["lats"], s: ["biceps", "core"]},
  stair_intervals: {p: ["conditioning"], s: ["quads", "glutes"]},
  stair_intervals_long: {p: ["conditioning"], s: ["quads", "glutes"]},
  stair_easy: {p: ["conditioning"], s: ["calves"]},
  incline_walk: {p: ["conditioning"], s: ["calves", "glutes"]},
  incline_power_walk: {p: ["conditioning"], s: ["glutes", "calves"]},
  jump_squat: {p: ["quads", "glutes"], s: ["calves"]},
  burpee: {p: ["full body"], s: ["chest", "quads"]},
  chair_stepup: {p: ["quads", "glutes"], s: []},
  stairwell_climb: {p: ["conditioning"], s: ["quads", "calves"]},
  skater_hop: {p: ["glutes", "quads"], s: ["ankles", "calves"]},
  squat_thrust: {p: ["full body"], s: ["core", "quads"]},
  pike_pushup: {p: ["shoulders", "triceps"], s: ["upper chest"]},
  broad_jump: {p: ["glutes", "quads"], s: ["hamstrings", "calves"]},
  hand_release_pushup: {p: ["chest", "triceps"], s: ["core"]},
  dead_hang: {p: ["grip", "lats"], s: ["shoulders", "spine"]},
  deep_squat_hold: {p: ["hips", "ankles"], s: ["quads"]},
  bear_crawl: {p: ["core", "shoulders"], s: ["quads"]},
  prone_ytw: {p: ["rear delts", "upper back"], s: ["rotator cuff"]},
  wall_sit: {p: ["quads"], s: ["glutes"]},
  cossack_squat: {p: ["adductors", "hips"], s: ["quads"]},
  hip_9090: {p: ["hips"], s: ["glutes"]},
  deep_squat_pry: {p: ["hips", "ankles"], s: ["adductors"]},
  couch_stretch: {p: ["hip flexors", "quads"], s: []},
  thoracic_ext_bench: {p: ["thoracic spine", "lats"], s: ["triceps"]},
  band_pull_apart: {p: ["rear delts", "upper back"], s: []},
  wall_slide: {p: ["shoulders", "upper back"], s: ["rotator cuff"]},
  childs_pose: {p: ["lower back", "lats"], s: ["hips"]},
  walk: {p: ["conditioning"], s: ["calves"]},
  pigeon: {p: ["glutes", "hips"], s: ["hip flexors"]},
  worlds_greatest: {p: ["hips", "thoracic spine"], s: ["hamstrings"]},
  cat_cow: {p: ["spine"], s: ["core"]},
  adductor_rockback: {p: ["adductors"], s: ["hips"]},
  scapular_pullup: {p: ["upper back", "lats"], s: ["grip"]},
  band_dislocate: {p: ["shoulders"], s: ["chest"]},
  scapular_pushup: {p: ["serratus", "shoulders"], s: []},
  frog_stretch: {p: ["adductors", "hips"], s: []},
  quadruped_t_rotation: {p: ["thoracic spine"], s: ["obliques"]},
  ankle_rock: {p: ["ankles", "calves"], s: []},
  active_hang: {p: ["lats", "grip"], s: ["shoulders"]},
  standing_forward_fold: {p: ["hamstrings", "spine"], s: ["calves"]}
};
