export const LOAD = {
  "pair": [
    "thruster",
    "bench_stepover",
    "burpee_over_bells",
    "punch_out",
    "man_maker",
    "devil_press",
    "hang_clean",
    "db_bent_row",
    "clean_and_press",
    "overhead_carry",
    "flat_db_press",
    "incline_db_press",
    "squeeze_press",
    "db_fly",
    "incline_db_fly",
    "cs_db_row",
    "seated_db_press",
    "standing_ohp",
    "arnold_press",
    "push_press",
    "lateral_raise",
    "seated_lateral_raise",
    "rear_delt_fly",
    "rear_delt_raise",
    "hammer_curl",
    "db_rdl",
    "stiff_leg_dl",
    "db_good_morning",
    "walking_lunge",
    "reverse_lunge",
    "bulgarian",
    "db_step_up",
    "lateral_lunge",
    "standing_calf",
    "seated_calf",
    "single_leg_calf",
    "db_shrug",
    "renegade_row",
    "farmer_carry",
    "db_front_squat",
    "shoulder_circles"
  ],
  "single": [
    "alt_snatch",
    "turkish_getup",
    "single_arm_press",
    "single_arm_floor_press",
    "goblet_cossack",
    "suitcase_deadlift",
    "jefferson_curl",
    "backpack_thruster",
    "backpack_row",
    "backpack_squat",
    "backpack_carry",
    "goblet_squat",
    "sumo_squat",
    "db_pullover",
    "single_arm_row",
    "concentration_curl",
    "oh_tri_ext",
    "tri_kickback",
    "cross_hammer_curl",
    "glute_bridge",
    "hip_thrust",
    "single_leg_rdl",
    "russian_twist",
    "decline_situp",
    "db_side_bend",
    "weighted_dead_bug",
    "suitcase_carry",
    "weighted_leg_raise",
    "twist_lunge",
    "back_extension"
  ],
  "bar": [
    "ez_curl",
    "ez_skullcrusher",
    "ez_upright_row",
    "ez_21s",
    "ez_oh_ext",
    "close_grip_press",
    "incline_curl"
  ],
  "stack": [
    "single_arm_cable_row",
    "cable_pull_through",
    "half_kneel_woodchop",
    "cable_rotation",
    "cable_antirotation_hold",
    "half_kneel_pulldown",
    "lat_pulldown",
    "seated_row",
    "cable_crossover",
    "cable_curl",
    "face_pull",
    "leg_curl",
    "cable_crunch",
    "woodchop",
    "pallof_press"
  ],
  "bw": [
    "jump_squat",
    "burpee",
    "chair_stepup",
    "stairwell_climb",
    "skater_hop",
    "squat_thrust",
    "battle_ropes",
    "pike_pushup",
    "broad_jump",
    "hand_release_pushup",
    "dead_hang",
    "deep_squat_hold",
    "bear_crawl",
    "prone_ytw",
    "wall_sit",
    "cossack_squat",
    "hip_9090",
    "deep_squat_pry",
    "couch_stretch",
    "thoracic_ext_bench",
    "band_pull_apart",
    "wall_slide",
    "childs_pose",
    "walk",
    "pigeon",
    "worlds_greatest",
    "cat_cow",
    "adductor_rockback",
    "scapular_pullup",
    "band_dislocate",
    "scapular_pushup",
    "frog_stretch",
    "quadruped_t_rotation",
    "ankle_rock",
    "active_hang",
    "standing_forward_fold",
    "pullup",
    "chinup",
    "wide_pullup",
    "pushup_burnout",
    "feet_elev_pushup",
    "diamond_pushup",
    "bench_dip",
    "inverted_row",
    "plank",
    "side_plank",
    "side_plank_reach",
    "copenhagen",
    "hollow_hold",
    "hollow_rock",
    "dead_bug",
    "bird_dog",
    "shoulder_taps",
    "plank_up_down",
    "ab_wheel",
    "mountain_climber",
    "flutter_kicks",
    "bicycle_crunch",
    "reverse_crunch",
    "v_up",
    "hanging_knee_raise",
    "hanging_leg_raise",
    "hanging_knee_twist",
    "toes_to_bar",
    "oblique_knee_raise",
    "archer_pushup",
    "wide_pushup",
    "spiderman_pushup"
  ],
  "level": [
    "stair_intervals",
    "stair_intervals_long",
    "stair_easy",
    "incline_walk"
  ]
};

export const PER = {
  "leg": [
    "cossack_squat",
    "goblet_cossack",
    "ankle_rock",
    "chair_stepup",
    "bulgarian",
    "walking_lunge",
    "reverse_lunge",
    "lateral_lunge",
    "db_step_up",
    "single_leg_rdl",
    "single_leg_calf"
  ],
  "arm": [
    "single_arm_press",
    "single_arm_floor_press",
    "single_arm_cable_row",
    "half_kneel_pulldown",
    "suitcase_deadlift",
    "backpack_row",
    "single_arm_row",
    "concentration_curl",
    "cross_hammer_curl",
    "renegade_row",
    "suitcase_carry"
  ],
  "side": [
    "turkish_getup",
    "half_kneel_woodchop",
    "cable_rotation",
    "cable_antirotation_hold",
    "hip_9090",
    "couch_stretch",
    "pigeon",
    "worlds_greatest",
    "quadruped_t_rotation",
    "side_plank",
    "side_plank_reach",
    "copenhagen",
    "bird_dog",
    "oblique_knee_raise",
    "woodchop",
    "pallof_press",
    "db_side_bend",
    "archer_pushup",
    "spiderman_pushup",
    "twist_lunge"
  ]
};

export const PATTERNS = {
  "Horizontal press":["hand_release_pushup","single_arm_floor_press","scapular_pushup","flat_db_press","incline_db_press","squeeze_press","pushup_burnout","feet_elev_pushup","diamond_pushup","close_grip_press","archer_pushup","wide_pushup","spiderman_pushup"],
  "Chest isolation":["db_fly","incline_db_fly","cable_crossover","db_pullover"],
  "Vertical pull":["half_kneel_pulldown","dead_hang","active_hang","scapular_pullup","pullup","chinup","wide_pullup","lat_pulldown"],
  "Horizontal pull":["db_bent_row","single_arm_cable_row","backpack_row","cs_db_row","single_arm_row","seated_row","renegade_row","inverted_row"],
  "Squat pattern":["goblet_cossack","backpack_squat","chair_stepup","wall_sit","goblet_squat","bulgarian","walking_lunge","db_front_squat","db_step_up","reverse_lunge","sumo_squat","lateral_lunge"],
  "Hip hinge":["cable_pull_through","suitcase_deadlift","db_rdl","single_leg_rdl","db_good_morning","stiff_leg_dl","glute_bridge","hip_thrust","leg_curl","back_extension"],
  "Calves":["standing_calf","seated_calf","single_leg_calf"],
  "Vertical press":["single_arm_press","pike_pushup","seated_db_press","standing_ohp","arnold_press","push_press"],
  "Lateral delts":["lateral_raise","seated_lateral_raise","ez_upright_row","shoulder_circles"],
  "Rear delts":["band_pull_apart","prone_ytw","rear_delt_fly","face_pull","rear_delt_raise"],
  "Biceps":["ez_curl","hammer_curl","cable_curl","incline_curl","concentration_curl","ez_21s","cross_hammer_curl"],
  "Triceps":["ez_skullcrusher","oh_tri_ext","bench_dip","ez_oh_ext","tri_kickback"],
  "Traps":["db_shrug"],
  "Core flexion":["hanging_knee_raise","hanging_leg_raise","bicycle_crunch","reverse_crunch","decline_situp","flutter_kicks","v_up","toes_to_bar","cable_crunch","weighted_leg_raise","hanging_knee_twist","oblique_knee_raise"],
  "Core bracing":["turkish_getup","bear_crawl","plank","side_plank","dead_bug","hollow_hold","shoulder_taps","ab_wheel","bird_dog","copenhagen","hollow_rock","side_plank_reach","weighted_dead_bug","plank_up_down","mountain_climber"],
  "Core rotation":["half_kneel_woodchop","cable_rotation","cable_antirotation_hold","russian_twist","woodchop","pallof_press","db_side_bend","twist_lunge"],
  "Conditioning":["thruster","bench_stepover","burpee_over_bells","punch_out","alt_snatch","man_maker","devil_press","hang_clean","clean_and_press","backpack_thruster","burpee","squat_thrust","battle_ropes"],
  "Plyometrics":["jump_squat","skater_hop","broad_jump"],
  "Machine cardio":["stair_intervals","stair_intervals_long","stair_easy","incline_walk","stairwell_climb","walk"],
  "Mobility":["cossack_squat","hip_9090","deep_squat_pry","deep_squat_hold","couch_stretch","thoracic_ext_bench","wall_slide","band_dislocate","childs_pose","pigeon","worlds_greatest","cat_cow","adductor_rockback","frog_stretch","jefferson_curl","quadruped_t_rotation","ankle_rock","standing_forward_fold"],
  "Carries":["overhead_carry","backpack_carry","suitcase_carry","farmer_carry"]
};

export const ALIASES = {
  archer_pushup: ["lateral push-ups", "side-to-side push-ups"],
  spiderman_pushup: ["spider-man push-ups"],
  shoulder_circles: ["arm circles", "shoulder rotations", "weighted shoulder rotations"],
  twist_lunge: ["standing plate twist", "lunge with twist", "lunge with torso rotation"],
  punch_out: ["shadowboxing", "weighted punches", "boxing with dumbbells"],
  turkish_getup: ["tgu", "get-up", "get up"],
  hip_9090: ["90 90", "90/90 stretch", "ninety ninety"],
  worlds_greatest: ["world's greatest stretch", "spiderman lunge with rotation"],
  back_extension: ["hyperextension", "hyperextensions", "45 degree back extension", "roman chair back extension"]
};

export const COMPOUND = [
  "Horizontal press", "Vertical press", "Vertical pull", "Horizontal pull",
  "Squat pattern", "Hip hinge", "Carries"
];
