export const LOAD = {
  "pair": [
    "flat_db_press",
    "incline_db_press",
    "squeeze_press",
    "db_fly",
    "incline_db_fly",
    "cs_db_row",
    "seated_db_press",
    "standing_ohp",
    "arnold_press",
    "push_press",
    "lateral_raise",
    "seated_lateral_raise",
    "rear_delt_fly",
    "rear_delt_raise",
    "hammer_curl",
    "db_rdl",
    "stiff_leg_dl",
    "db_good_morning",
    "walking_lunge",
    "reverse_lunge",
    "bulgarian",
    "db_step_up",
    "lateral_lunge",
    "standing_calf",
    "seated_calf",
    "single_leg_calf",
    "db_shrug",
    "renegade_row",
    "farmer_carry",
    "db_front_squat"
  ],
  "single": [
    "goblet_squat",
    "sumo_squat",
    "db_pullover",
    "single_arm_row",
    "concentration_curl",
    "oh_tri_ext",
    "tri_kickback",
    "cross_hammer_curl",
    "glute_bridge",
    "hip_thrust",
    "single_leg_rdl",
    "russian_twist",
    "decline_situp",
    "db_side_bend",
    "weighted_dead_bug",
    "suitcase_carry",
    "weighted_leg_raise"
  ],
  "bar": [
    "ez_curl",
    "ez_skullcrusher",
    "ez_upright_row",
    "ez_21s",
    "ez_oh_ext",
    "close_grip_press",
    "incline_curl"
  ],
  "stack": [
    "lat_pulldown",
    "seated_row",
    "cable_crossover",
    "cable_curl",
    "face_pull",
    "leg_curl",
    "cable_crunch",
    "woodchop",
    "pallof_press"
  ],
  "bw": [
    "pullup",
    "chinup",
    "wide_pullup",
    "pushup_burnout",
    "feet_elev_pushup",
    "diamond_pushup",
    "bench_dip",
    "inverted_row",
    "plank",
    "side_plank",
    "side_plank_reach",
    "copenhagen",
    "hollow_hold",
    "hollow_rock",
    "dead_bug",
    "bird_dog",
    "shoulder_taps",
    "plank_up_down",
    "ab_wheel",
    "mountain_climber",
    "flutter_kicks",
    "bicycle_crunch",
    "reverse_crunch",
    "v_up",
    "hanging_knee_raise",
    "hanging_leg_raise",
    "hanging_knee_twist",
    "toes_to_bar",
    "oblique_knee_raise"
  ]
};

export const PER = {
  "leg": [
    "bulgarian",
    "walking_lunge",
    "reverse_lunge",
    "lateral_lunge",
    "db_step_up",
    "single_leg_rdl",
    "single_leg_calf"
  ],
  "arm": [
    "single_arm_row",
    "concentration_curl",
    "cross_hammer_curl",
    "renegade_row",
    "suitcase_carry"
  ],
  "side": [
    "side_plank",
    "side_plank_reach",
    "copenhagen",
    "bird_dog",
    "oblique_knee_raise",
    "woodchop",
    "pallof_press",
    "db_side_bend"
  ]
};

export const PATTERNS = {
  "Horizontal press":["flat_db_press","incline_db_press","squeeze_press","pushup_burnout","feet_elev_pushup","diamond_pushup","close_grip_press"],
  "Chest isolation":["db_fly","incline_db_fly","cable_crossover","db_pullover"],
  "Vertical pull":["pullup","chinup","wide_pullup","lat_pulldown"],
  "Horizontal pull":["cs_db_row","single_arm_row","seated_row","renegade_row","inverted_row"],
  "Squat pattern":["goblet_squat","bulgarian","walking_lunge","db_front_squat","db_step_up","reverse_lunge","sumo_squat","lateral_lunge"],
  "Hip hinge":["db_rdl","single_leg_rdl","db_good_morning","stiff_leg_dl","glute_bridge","hip_thrust","leg_curl"],
  "Calves":["standing_calf","seated_calf","single_leg_calf"],
  "Vertical press":["seated_db_press","standing_ohp","arnold_press","push_press"],
  "Lateral delts":["lateral_raise","seated_lateral_raise","ez_upright_row"],
  "Rear delts":["rear_delt_fly","face_pull","rear_delt_raise"],
  "Biceps":["ez_curl","hammer_curl","cable_curl","incline_curl","concentration_curl","ez_21s","cross_hammer_curl"],
  "Triceps":["ez_skullcrusher","oh_tri_ext","bench_dip","ez_oh_ext","tri_kickback"],
  "Traps":["db_shrug"],
  "Core flexion":["hanging_knee_raise","hanging_leg_raise","bicycle_crunch","reverse_crunch","decline_situp","flutter_kicks","v_up","toes_to_bar","cable_crunch","weighted_leg_raise","hanging_knee_twist","oblique_knee_raise"],
  "Core bracing":["plank","side_plank","dead_bug","hollow_hold","shoulder_taps","ab_wheel","bird_dog","copenhagen","hollow_rock","side_plank_reach","weighted_dead_bug","plank_up_down","mountain_climber"],
  "Core rotation":["russian_twist","woodchop","pallof_press","db_side_bend"],
  "Carries":["suitcase_carry","farmer_carry"]
};
